name: xml_widget_creator
description: widget creating tool from xml

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  xml: ^3.3.1
  args: ^1.5.1
  recase: ^2.0.1
dev_dependencies:
  test: ^1.5.3